Desafio Nintendo
Aspectos a incluir

1.Abra o arquivo "best-selling game consoles.xlsx" em um dataframe.
Substitua a palavra "NES" por "Nintendinho" no nome dos consoles e deixe todos os nomes em maiúsculos.
2.Filtre o nome dos consoles com data de release depois de 2010.
3.De um describe e info da base, substitua os missing values pela string "missing".
4.Filtre os consoles que foram descontinuados a menos de 2 anos da data de release.

In [46]:
import pandas as pd

# Lê o arquivo Excel em um DataFrame
dataframe = pd.read_excel('best-selling game consoles.xlsx', sheet_name='consoles')

dataframe['Console Name'] = dataframe['Console Name'].str.replace('NES', 'Nintendinho').str.upper()

dataframe_filtrado = dataframe[dataframe['Released Year'] > 2010]


dataframe_filtrado.fillna("missing", inplace=True)

dataframe_filtrado

# Calcula a diferença entre as datas de descontinuação e lançamento
dataframe_filtrado['Diff Years Launch'] = dataframe_filtrado['Discontinuation Year'] - dataframe_filtrado['Released Year']

# Filtra os consoles descontinuados a menos de 2 anos do lançamento
consoles_descontinuados = dataframe_filtrado[dataframe_filtrado['Diff Years Launch'] <= 2]

consoles_descontinuados

# Exibe os consoles descontinuados a menos de 2 anos do lançamento
#print(consoles_descontinuados)


# Exibe informações sobre o DataFrame (describe e info)
# print(dataframe_filtrado.describe())
#  print(dataframe_filtrado.info())

# Exibe as primeiras linhas do DataFrame
#print(dataframe.head())

C:\Users\felis\AppData\Local\Temp\ipykernel_10204\1271138275.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe_filtrado.fillna("missing", inplace=True)
C:\Users\felis\AppData\Local\Temp\ipykernel_10204\1271138275.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe_filtrado['Diff Years Launch'] = dataframe_filtrado['Discontinuation Year'] - dataframe_filtrado['Released Year']

,Console Name,Type,Company,Released Year,Discontinuation Year,Units sold (million),Remarks,Diff Years Launch
2,NINTENDO SWITCH,Hybrid,Nintendo,2017,0,122.55,missing,-2017
5,PLAYSTATION 4,Home,Sony,2013,0,117.20,missing,-2013
19,PLAYSTATION 5,Home,Sony,2020,0,30.00,missing,-2020
23,XBOX SERIES X/S,Home,Microsoft,2020,0,18.50,Approximately around 18.5 million,-2020
33,SUPER NINTENDINHO CLASSIC EDITION,Dedicated,Nintendo,2017,2018,5.28,missing,1
35,NINTENDINHO CLASSIC EDITION,Dedicated,Nintendo,2016,2018,3.56,missing,2